-- Create trained_models table
CREATE TABLE IF NOT EXISTS trained_models (
  id TEXT PRIMARY KEY,
  user_id TEXT,
  name TEXT,
  model_name TEXT,
  description TEXT,
  version TEXT,
  model_url TEXT,
  status TEXT NOT NULL,
  error_message TEXT,
  progress INTEGER DEFAULT 0,
  model_info JSONB,
  sample_image TEXT,
  input_data JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  keyword TEXT,
  input_parameters JSONB,
  category TEXT,
  is_public BOOLEAN DEFAULT FALSE,
  replicate_id TEXT,
  last_used TIMESTAMP WITH TIME ZONE,
  thumbnail_url TEXT
);

-- Create indexes
CREATE INDEX IF NOT EXISTS trained_models_status_idx ON trained_models(status);
CREATE INDEX IF NOT EXISTS trained_models_created_at_idx ON trained_models(created_at);
CREATE INDEX IF NOT EXISTS trained_models_category_idx ON trained_models(category);
CREATE INDEX IF NOT EXISTS trained_models_user_id_idx ON trained_models(user_id);

-- Create RLS policies
-- Enable RLS
ALTER TABLE trained_models ENABLE ROW LEVEL SECURITY;

-- Create policy for anyone to read public models
CREATE POLICY "Anyone can read public models"
  ON trained_models
  FOR SELECT
  USING (is_public = TRUE);

-- Create policy for authenticated users to read their own models
CREATE POLICY "Authenticated users can read their own models"
  ON trained_models
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

-- Create policy for authenticated users to insert their own models
CREATE POLICY "Authenticated users can insert their own models"
  ON trained_models
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- Create policy for authenticated users to update their own models
CREATE POLICY "Authenticated users can update their own models"
  ON trained_models
  FOR UPDATE
  USING (auth.uid() IS NOT NULL);

-- Create policy for authenticated users to delete their own models
CREATE POLICY "Authenticated users can delete their own models"
  ON trained_models
  FOR DELETE
  USING (auth.uid() IS NOT NULL);

-- Comments for documentation
COMMENT ON TABLE trained_models IS 'Custom trained models for the application';
COMMENT ON COLUMN trained_models.id IS 'Unique identifier for the model';
COMMENT ON COLUMN trained_models.user_id IS 'User who created the model';
COMMENT ON COLUMN trained_models.model_url IS 'URL to the trained model on Replicate or other platform';
COMMENT ON COLUMN trained_models.status IS 'Status of the model: starting, training, completed, failed';
COMMENT ON COLUMN trained_models.error_message IS 'Error message if the training failed';
COMMENT ON COLUMN trained_models.progress IS 'Training progress percentage';
COMMENT ON COLUMN trained_models.model_info IS 'Detailed information about the model';
COMMENT ON COLUMN trained_models.sample_image IS 'Base64 encoded sample image generated by the model';
COMMENT ON COLUMN trained_models.keyword IS 'Trigger word to use this model in prompts';
COMMENT ON COLUMN trained_models.input_parameters IS 'Parameters used during training'; 